Traceback (most recent call last):
  File "C:\TTR-Private-Animation-Adict\toontown\ai\ServiceStartAI.py", line 58, in <module>
    run()
  File "C:\TTR-Private-Animation-Adict\otp\ai\AIBase.py", line 194, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 540, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 494, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.11.0-x64\direct\distributed\ConnectionRepository.py", line 617, in readerPollOnce
    if self.checkDatagram():
  File "C:\TTR-Private-Animation-Adict\toontown\battle\DistributedBattleBaseAI.py", line 1079, in requestAttack
    self.__requestMovie()
  File "C:\TTR-Private-Animation-Adict\toontown\battle\DistributedBattleBaseAI.py", line 1144, in __requestMovie
    self.__makeMovie()
  File "C:\TTR-Private-Animation-Adict\toontown\battle\DistributedBattleBaseAI.py", line 1170, in __makeMovie
    self.battleCalc.calculateRound()
  File "C:\TTR-Private-Animation-Adict\toontown\battle\BattleCalculatorAI.py", line 1391, in calculateRound
    self.__calculateSuitAttacks()
  File "C:\TTR-Private-Animation-Adict\toontown\battle\BattleCalculatorAI.py", line 1257, in __calculateSuitAttacks
    self.__calcSuitAtkHp(i)
  File "C:\TTR-Private-Animation-Adict\toontown\battle\BattleCalculatorAI.py", line 1176, in __calcSuitAtkHp
    if 'cogs-weaken' in self.battle.statusEffects:
AttributeError: 'DistributedBattleAI' object has no attribute 'statusEffects'

