Traceback (most recent call last):
  File "C:\Toontown\Toontown - Programming\TTR-Private-AnimationAdict\TTR-Private-Animation-Adict\toontown\ai\ServiceStartAI.py", line 58, in <module>
    run()
  File "C:\Toontown\Toontown - Programming\TTR-Private-AnimationAdict\TTR-Private-Animation-Adict\otp\ai\AIBase.py", line 194, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 540, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 494, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.11.0-x64\direct\distributed\ConnectionRepository.py", line 619, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\AstronInternalRepository.py", line 232, in handleDatagram
    self.handleObjEntry(di, msgType == STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED_OTHER)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\AstronInternalRepository.py", line 298, in handleObjEntry
    do.updateAllRequiredOtherFields(dclass, di)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 265, in updateAllRequiredOtherFields
    dclass.receiveUpdateOther(self, di)
TypeError: setState() takes 2 positional arguments but 3 were given

